# .project metadata for Microcks
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

schema_version: "1.0.0"
slug: "microcks"
name: "Microcks"
description: "The open source, cloud native tool for API Mocking and Testing"
type: "project"
project_lead:
  - "lbroudoux"
  - "yada"
  - "SebastienDegodez"
slack_channels:
  - name: "#microcks"
    workspace: "cncf"
    link: "https://cloud-native.slack.com/messages/microcks"
    primary: true

maturity_log:
  - phase: "sandbox"
    date: "2023-06-22T00:00:00Z"
    issue: "https://github.com/cncf/sandbox/issues/37"
  - phase: "incubating"
    date: "2026-05-03T00:00:00Z"
    issue: "https://github.com/cncf/toc/issues/1552"

repositories:
  - "https://github.com/microcks/microcks"

website: "https://microcks.io"

artwork: "https://github.com/cncf/artwork/blob/main/examples/incubating.md#microcks-logos"

adopters:
  path: "https://github.com/microcks/microcks/blob/master/ADOPTERS.md"

package_managers:
  docker:
    - "quay.io/microcks/microcks"
    - "docker.io/microcks/microcks"
    - "quay.io/microcks/microcks-async-minion"
    - "docker.io/microcks/microcks-async-minion"
    - "quay.io/microcks/microcks-postman-runtime"
    - "docker.io/microcks/microcks-postman-runtime"
    - "quay.io/microcks/microcks-uber"
    - "docker.io/microcks/microcks-uber"
    - "quay.io/microcks/microcks-uber-async-minion"
    - "docker.io/microcks/microcks-uber-async-minion"
    - "quay.io/microcks/microcks-operator"
    - "docker.io/microcks/microcks-operator"
    - "quay.io/microcks/microcks-cli"
    - "docker.io/microcks/microcks-cli"
  helm: "microcks/microcks"
  homebrew:
    - "microcks/tap/microcks"
  maven:
    - "io.github.microcks:microcks"
    - "io.github.microcks:microcks-app"
    - "io.github.microcks:microcks-async-minion"
    - "io.github.microcks:microcks-distro"
    - "io.github.microcks:microcks-el"
    - "io.github.microcks:microcks-java-client"
    - "io.github.microcks:microcks-jenkins-plugin"
    - "io.github.microcks:microcks-kube-api"
    - "io.github.microcks:microcks-kube-operator"
    - "io.github.microcks:microcks-model"
    - "io.github.microcks:microcks-operator"
    - "io.github.microcks:microcks-testcontainers"
    - "io.github.microcks:microcks-uber-app"
    - "io.github.microcks:microcks-uber-async-minion"
    - "io.github.microcks:microcks-util"
    - "io.github.microcks.quarkus:quarkus-microcks"
    - "io.github.microcks.quarkus:quarkus-microcks-deployment"
    - "io.github.microcks.quarkus:quarkus-microcks-parent"
    - "io.github.microcks.quarkus:quarkus-microcks-test"
  npm:
    - "@microcks/microcks-backstage-provider"
    - "@microcks/microcks-testcontainers"
    - "@microcks/spectral-ruleset"
  nuget:
    - "Microcks.Aspire"
    - "Microcks.Testcontainers"

social:
  twitter: "https://twitter.com/microcksio"

security:
  policy:
    path: "https://github.com/microcks/microcks/blob/master/SECURITY.md"
  contact:
    email: "security@microcks.io"

governance:
  contributing:
    path: "https://github.com/microcks/microcks/blob/master/CONTRIBUTING.md"
  code_of_conduct:
    path: "https://github.com/microcks/microcks/blob/master/CODE_OF_CONDUCT.md"

legal:
  license:
    path: "https://github.com/microcks/microcks/blob/master/LICENSE"
  identity_type:
    has_dco: true
    has_cla: false
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/microcks/microcks/blob/master/README.md"

landscape:
  category: "App Definition and Development"
  subcategory: "Application Definition & Image Build"

# CLOMonitor Score: 98/100
# Documentation: 100 | License: 100 | Best Practices: 96 | Security: 95
